version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: product_importer_local_django
    container_name: pi_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: product_importer_production_postgres
    container_name: pi_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: pi_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: pi_redis

  celeryworker:
    <<: *django
    image: product_importer_local_celeryworker
    container_name: pi_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  flower:
    <<: *django
    image: product_importer_local_flower
    container_name: pi_flower
    ports:
      - "5555:5555"
    command: /start-flower
